# Project information
site_name: 'ISCC Foundation'
site_description: 'An open, decentralized content identifier'
site_author: 'Sebastian Posth, Titusz Pan'
site_url: 'https://iscc.foundation'


# Copyright
copyright: 'Copyright © 2019 ISCC Foundation'

# Docs and Theme
theme:
    name: 'material'
    custom_dir: 'theme'
    language: 'en'
    favicon: 'images/favicon.ico'
    logo: 'images/iscc-icon-white.svg'
    feature:
        tabs: false
    palette:
        primary: 'Blue Grey'
        accent: 'pink'
    font:
        text: 'Open Sans'
        code: 'Source Code Pro'

# Navigation
nav:
    - About the Foundation: 'index.md'
    - About the ISCC: 'iscc.md'
    - Become a Supporter: 'support.md'
    - News:
          - '2019-05-22': 'news/2019-05-22.md'

# Options
extra:
    search:
        language: 'en'
    social:
        - type: 'home'
          link: '/'
        - type: 'github'
          link: 'https://github.com/iscc'
extra_css:
  - 'styles/extra.css'

markdown_extensions:
    - markdown.extensions.abbr
    - markdown.extensions.attr_list
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
        linenums: false
        guess_lang: false
    - markdown.extensions.attr_list
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: '#'
    - pymdownx.magiclink
