# Project information
site_name: 'ISCC Foundation'
site_description: 'Open and decentralized content identification.'
site_author: 'Sebastian Posth, Titusz Pan'
site_url: 'https://iscc.foundation'

# Repository
repo_name: 'iscc/foundation'
repo_url: 'https://github.com/iscc/foundation'
edit_uri: 'edit/main/docs/'

# Copyright
copyright: 'Copyright © 2019-2022 ISCC Foundation
| <a href="/privacy">Privacy Policy</a>
| <a href="/cookies">Cookie Policy</a>
| <a href="/imprint">Imprint</a>
| <a href="/disclaimer">Disclaimer</a>'

# Docs and Theme
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  logo: images/iscc-logo-icon-white.svg
  favicon: images/iscc-logo-icon-black.svg
  font:
    text: Readex Pro
    code: JetBrains Mono
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top

extra_css:
  - 'styles/extra.css'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.tabbed
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: '#'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iscc
    - icon: fontawesome/brands/telegram
      link: https://t.me/iscc_dev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iscc_foundation
  analytics:
    provider: custom

nav:
  - ISCC Foundation: index.md
  - ISCC: iscc.md
  - Board: board.md
  - Supporters: support.md
  - News:
      - "2020-02-16": news/2020-02-16.md
      - "2019-05-22": news/2019-05-23.md
