# Project information
site_name: 'ISCC Foundation'
site_description: 'An open, decentralized content identifier'
site_author: 'Sebastian Posth, Titusz Pan'
site_url: 'https://iscc.foundation'

# Copyright
copyright: 'Copyright © 2019-2020 ISCC Foundation'

# Docs and Theme
theme:
    name: 'material'
    custom_dir: 'theme'
    language: 'en'
    favicon: 'images/favicon.ico'
    logo: 'images/iscc-icon-white.svg'
    feature:
        tabs: false
    palette:
        primary: 'Blue Grey'
        accent: 'pink'
    font:
        text: 'Open Sans'
        code: 'Source Code Pro'

nav:
    - About ISCC: iscc.md
    - About the Foundation: index.md
    - Board Members: board.md
    - Become a Supporter: support.md
    - News:
          - "2020-02-16": news/2020-02-16.md
          - "2019-05-22": news/2019-05-23.md

extra_css:
  - 'styles/extra.css'

markdown_extensions:
  - attr_list
  - pymdownx.magiclink
  - pymdownx.tabbed
  - markdown.extensions.meta
  - markdown.extensions.toc:
        permalink: '#'

